# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newObject.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UiNewObjectWindow(object):
    def setupUi(self, newObjectWindow):
        newObjectWindow.setObjectName("newObjectWindow")
        newObjectWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        newObjectWindow.resize(390, 629)
        self.centralwidget = QtWidgets.QWidget(newObjectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(30, 9, 30, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.base_width = QtWidgets.QSpinBox(self.centralwidget)
        self.base_width.setAlignment(QtCore.Qt.AlignCenter)
        self.base_width.setMinimum(100)
        self.base_width.setMaximum(500)
        self.base_width.setProperty("value", 100)
        self.base_width.setObjectName("base_width")
        self.verticalLayout.addWidget(self.base_width)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.base_length = QtWidgets.QSpinBox(self.centralwidget)
        self.base_length.setAlignment(QtCore.Qt.AlignCenter)
        self.base_length.setSpecialValueText("")
        self.base_length.setMinimum(60)
        self.base_length.setMaximum(500)
        self.base_length.setProperty("value", 60)
        self.base_length.setObjectName("base_length")
        self.verticalLayout.addWidget(self.base_length)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.base_height = QtWidgets.QSpinBox(self.centralwidget)
        self.base_height.setAlignment(QtCore.Qt.AlignCenter)
        self.base_height.setSpecialValueText("")
        self.base_height.setMinimum(4)
        self.base_height.setMaximum(100)
        self.base_height.setObjectName("base_height")
        self.verticalLayout.addWidget(self.base_height)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.columns_count = QtWidgets.QSpinBox(self.centralwidget)
        self.columns_count.setAlignment(QtCore.Qt.AlignCenter)
        self.columns_count.setSpecialValueText("")
        self.columns_count.setMaximum(3)
        self.columns_count.setObjectName("columns_count")
        self.verticalLayout.addWidget(self.columns_count)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.column_height = QtWidgets.QSpinBox(self.centralwidget)
        self.column_height.setEnabled(False)
        self.column_height.setAlignment(QtCore.Qt.AlignCenter)
        self.column_height.setSpecialValueText("")
        self.column_height.setMinimum(30)
        self.column_height.setMaximum(500)
        self.column_height.setObjectName("column_height")
        self.verticalLayout.addWidget(self.column_height)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.top_tower_size = QtWidgets.QSpinBox(self.centralwidget)
        self.top_tower_size.setAlignment(QtCore.Qt.AlignCenter)
        self.top_tower_size.setSpecialValueText("")
        self.top_tower_size.setMinimum(20)
        self.top_tower_size.setMaximum(500)
        self.top_tower_size.setObjectName("top_tower_size")
        self.verticalLayout.addWidget(self.top_tower_size)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.bottom_tower_size = QtWidgets.QSpinBox(self.centralwidget)
        self.bottom_tower_size.setAlignment(QtCore.Qt.AlignCenter)
        self.bottom_tower_size.setSpecialValueText("")
        self.bottom_tower_size.setMinimum(30)
        self.bottom_tower_size.setMaximum(500)
        self.bottom_tower_size.setObjectName("bottom_tower_size")
        self.verticalLayout.addWidget(self.bottom_tower_size)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.tower_height = QtWidgets.QSpinBox(self.centralwidget)
        self.tower_height.setAlignment(QtCore.Qt.AlignCenter)
        self.tower_height.setSpecialValueText("")
        self.tower_height.setMinimum(50)
        self.tower_height.setMaximum(500)
        self.tower_height.setObjectName("tower_height")
        self.verticalLayout.addWidget(self.tower_height)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.hats_count = QtWidgets.QSpinBox(self.centralwidget)
        self.hats_count.setAlignment(QtCore.Qt.AlignCenter)
        self.hats_count.setSpecialValueText("")
        self.hats_count.setMaximum(5)
        self.hats_count.setObjectName("hats_count")
        self.verticalLayout.addWidget(self.hats_count)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.tower_hat_size = QtWidgets.QSpinBox(self.centralwidget)
        self.tower_hat_size.setEnabled(False)
        self.tower_hat_size.setAlignment(QtCore.Qt.AlignCenter)
        self.tower_hat_size.setSpecialValueText("")
        self.tower_hat_size.setMaximum(500)
        self.tower_hat_size.setObjectName("tower_hat_size")
        self.verticalLayout.addWidget(self.tower_hat_size)
        self.make_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.make_button.setFont(font)
        self.make_button.setObjectName("make_button")
        self.verticalLayout.addWidget(self.make_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        newObjectWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(newObjectWindow)
        QtCore.QMetaObject.connectSlotsByName(newObjectWindow)

    def retranslateUi(self, newObjectWindow):
        _translate = QtCore.QCoreApplication.translate
        newObjectWindow.setWindowTitle(_translate("newObjectWindow", "Параметры нового объекта"))
        self.label.setText(_translate("newObjectWindow", "Ширина основания:"))
        self.label_2.setText(_translate("newObjectWindow", "Длина основания:"))
        self.label_8.setText(_translate("newObjectWindow", "Высота основания:"))
        self.label_3.setText(_translate("newObjectWindow", "Кол-во колонн с одной стороны:"))
        self.label_5.setText(_translate("newObjectWindow", "Высота колонн:"))
        self.label_6.setText(_translate("newObjectWindow", "Размер верхнего основания башни:"))
        self.label_7.setText(_translate("newObjectWindow", "Размер нижнего основания башни:"))
        self.label_11.setText(_translate("newObjectWindow", "Высота башни:"))
        self.label_9.setText(_translate("newObjectWindow", "Кол-во блоков верхушек башен:"))
        self.label_10.setText(_translate("newObjectWindow", "Размер первого блока верхушек башен:"))
        self.make_button.setText(_translate("newObjectWindow", "Создать"))
