# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openMF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UiOpenMFWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/3d-modeling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rotateY = QtWidgets.QSlider(self.layoutWidget)
        self.rotateY.setMaximum(360)
        self.rotateY.setSingleStep(10)
        self.rotateY.setOrientation(QtCore.Qt.Horizontal)
        self.rotateY.setObjectName("rotateY")
        self.verticalLayout.addWidget(self.rotateY)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rotateX = QtWidgets.QSlider(self.layoutWidget)
        self.rotateX.setMaximum(360)
        self.rotateX.setSingleStep(10)
        self.rotateX.setOrientation(QtCore.Qt.Vertical)
        self.rotateX.setTickInterval(0)
        self.rotateX.setObjectName("rotateX")
        self.horizontalLayout.addWidget(self.rotateX)
        self.scene_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_label.sizePolicy().hasHeightForWidth())
        self.scene_label.setSizePolicy(sizePolicy)
        self.scene_label.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.scene_label.setText("")
        self.scene_label.setScaledContents(True)
        self.scene_label.setObjectName("scene_label")
        self.horizontalLayout.addWidget(self.scene_label)
        self.rotateZ = QtWidgets.QSlider(self.layoutWidget)
        self.rotateZ.setMaximum(360)
        self.rotateZ.setSingleStep(10)
        self.rotateZ.setOrientation(QtCore.Qt.Vertical)
        self.rotateZ.setObjectName("rotateZ")
        self.horizontalLayout.addWidget(self.rotateZ)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.command_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.command_edit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.command_edit.setFont(font)
        self.command_edit.setFrame(False)
        self.command_edit.setObjectName("command_edit")
        self.verticalLayout.addWidget(self.command_edit)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon1)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_3.setIcon(icon2)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_4.setIcon(icon3)
        self.action_4.setObjectName("action_4")
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openMF"))
        self.command_edit.setPlaceholderText(_translate("MainWindow", "Введите команду..."))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action_2.setText(_translate("MainWindow", "Загрузить объект"))
        self.action_3.setText(_translate("MainWindow", "Сохранить объект"))
        self.action_4.setText(_translate("MainWindow", "Выход"))
