# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openMF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UiOpenMFWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/img/3d-modeling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rotateYslider = QtWidgets.QSlider(self.layoutWidget)
        self.rotateYslider.setMaximum(360)
        self.rotateYslider.setSingleStep(10)
        self.rotateYslider.setOrientation(QtCore.Qt.Horizontal)
        self.rotateYslider.setObjectName("rotateYslider")
        self.verticalLayout.addWidget(self.rotateYslider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rotateXslider = QtWidgets.QSlider(self.layoutWidget)
        self.rotateXslider.setMaximum(360)
        self.rotateXslider.setSingleStep(10)
        self.rotateXslider.setOrientation(QtCore.Qt.Vertical)
        self.rotateXslider.setTickInterval(0)
        self.rotateXslider.setObjectName("rotateXslider")
        self.horizontalLayout.addWidget(self.rotateXslider)
        self.scene_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_label.sizePolicy().hasHeightForWidth())
        self.scene_label.setSizePolicy(sizePolicy)
        self.scene_label.setMinimumSize(QtCore.QSize(300, 300))
        self.scene_label.setText("")
        self.scene_label.setScaledContents(True)
        self.scene_label.setObjectName("scene_label")
        self.horizontalLayout.addWidget(self.scene_label)
        self.rotateZslider = QtWidgets.QSlider(self.layoutWidget)
        self.rotateZslider.setMaximum(360)
        self.rotateZslider.setSingleStep(10)
        self.rotateZslider.setOrientation(QtCore.Qt.Vertical)
        self.rotateZslider.setObjectName("rotateZslider")
        self.horizontalLayout.addWidget(self.rotateZslider)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.command_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.command_edit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.command_edit.setFont(font)
        self.command_edit.setFrame(False)
        self.command_edit.setObjectName("command_edit")
        self.verticalLayout.addWidget(self.command_edit)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.manipulatingContainer = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.manipulatingContainer.setContentsMargins(0, 0, 0, 0)
        self.manipulatingContainer.setObjectName("manipulatingContainer")
        self.widget = QtWidgets.QWidget(self.layoutWidget1)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.objectsBox = QtWidgets.QComboBox(self.widget)
        self.objectsBox.setStyleSheet("font: 75 8pt \"Sitka\";")
        self.objectsBox.setObjectName("objectsBox")
        self.verticalLayout_2.addWidget(self.objectsBox)
        self.addObject = QtWidgets.QPushButton(self.widget)
        self.addObject.setStyleSheet("font: 75 10pt \"Sitka\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/img/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addObject.setIcon(icon1)
        self.addObject.setIconSize(QtCore.QSize(25, 25))
        self.addObject.setObjectName("addObject")
        self.verticalLayout_2.addWidget(self.addObject)
        self.removeObject = QtWidgets.QPushButton(self.widget)
        self.removeObject.setStyleSheet("font: 75 10pt \"Sitka\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/img/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeObject.setIcon(icon2)
        self.removeObject.setIconSize(QtCore.QSize(25, 25))
        self.removeObject.setObjectName("removeObject")
        self.verticalLayout_2.addWidget(self.removeObject, 0, QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.eye_x = QtWidgets.QDoubleSpinBox(self.widget)
        self.eye_x.setMinimum(-99.99)
        self.eye_x.setObjectName("eye_x")
        self.horizontalLayout_4.addWidget(self.eye_x)
        self.eye_y = QtWidgets.QDoubleSpinBox(self.widget)
        self.eye_y.setMinimum(-99.99)
        self.eye_y.setObjectName("eye_y")
        self.horizontalLayout_4.addWidget(self.eye_y)
        self.eye_z = QtWidgets.QDoubleSpinBox(self.widget)
        self.eye_z.setMinimum(-99.99)
        self.eye_z.setProperty("value", 1.0)
        self.eye_z.setObjectName("eye_z")
        self.horizontalLayout_4.addWidget(self.eye_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.eye_set = QtWidgets.QPushButton(self.widget)
        self.eye_set.setObjectName("eye_set")
        self.verticalLayout_2.addWidget(self.eye_set)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.center_x = QtWidgets.QDoubleSpinBox(self.widget)
        self.center_x.setMinimum(-99.99)
        self.center_x.setObjectName("center_x")
        self.horizontalLayout_6.addWidget(self.center_x)
        self.center_y = QtWidgets.QDoubleSpinBox(self.widget)
        self.center_y.setMinimum(-99.99)
        self.center_y.setObjectName("center_y")
        self.horizontalLayout_6.addWidget(self.center_y)
        self.center_z = QtWidgets.QDoubleSpinBox(self.widget)
        self.center_z.setMinimum(-99.99)
        self.center_z.setObjectName("center_z")
        self.horizontalLayout_6.addWidget(self.center_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.center_set = QtWidgets.QPushButton(self.widget)
        self.center_set.setObjectName("center_set")
        self.verticalLayout_2.addWidget(self.center_set)
        self.aroundCenter = QtWidgets.QRadioButton(self.widget)
        self.aroundCenter.setChecked(True)
        self.aroundCenter.setObjectName("aroundCenter")
        self.verticalLayout_2.addWidget(self.aroundCenter)
        self.aroundEye = QtWidgets.QRadioButton(self.widget)
        self.aroundEye.setObjectName("aroundEye")
        self.verticalLayout_2.addWidget(self.aroundEye)
        self.manipulatingContainer.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scaleBoxX = QtWidgets.QDoubleSpinBox(self.widget1)
        self.scaleBoxX.setStyleSheet("font: 75 10pt \"Sitka\";")
        self.scaleBoxX.setMinimum(1.0)
        self.scaleBoxX.setMaximum(2.0)
        self.scaleBoxX.setSingleStep(0.01)
        self.scaleBoxX.setObjectName("scaleBoxX")
        self.horizontalLayout_2.addWidget(self.scaleBoxX)
        self.scaleBoxY = QtWidgets.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.scaleBoxY.setFont(font)
        self.scaleBoxY.setStyleSheet("font: 75 10pt \"Sitka\";")
        self.scaleBoxY.setMinimum(1.0)
        self.scaleBoxY.setMaximum(2.0)
        self.scaleBoxY.setSingleStep(0.01)
        self.scaleBoxY.setObjectName("scaleBoxY")
        self.horizontalLayout_2.addWidget(self.scaleBoxY)
        self.scaleBoxZ = QtWidgets.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.scaleBoxZ.setFont(font)
        self.scaleBoxZ.setStyleSheet("font: 75 10pt \"Sitka\";")
        self.scaleBoxZ.setMinimum(1.0)
        self.scaleBoxZ.setMaximum(2.0)
        self.scaleBoxZ.setSingleStep(0.01)
        self.scaleBoxZ.setObjectName("scaleBoxZ")
        self.horizontalLayout_2.addWidget(self.scaleBoxZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scaleButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.scaleButton.setFont(font)
        self.scaleButton.setStyleSheet("font: 75 12pt \"Sitka\";")
        self.scaleButton.setObjectName("scaleButton")
        self.verticalLayout_3.addWidget(self.scaleButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.moveBoxX = QtWidgets.QSpinBox(self.widget1)
        self.moveBoxX.setMinimum(-1000)
        self.moveBoxX.setMaximum(1000)
        self.moveBoxX.setObjectName("moveBoxX")
        self.horizontalLayout_3.addWidget(self.moveBoxX)
        self.moveBoxY = QtWidgets.QSpinBox(self.widget1)
        self.moveBoxY.setMinimum(-1000)
        self.moveBoxY.setMaximum(1000)
        self.moveBoxY.setObjectName("moveBoxY")
        self.horizontalLayout_3.addWidget(self.moveBoxY)
        self.moveBoxZ = QtWidgets.QSpinBox(self.widget1)
        self.moveBoxZ.setMinimum(-1000)
        self.moveBoxZ.setMaximum(1000)
        self.moveBoxZ.setObjectName("moveBoxZ")
        self.horizontalLayout_3.addWidget(self.moveBoxZ)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.moveButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.moveButton.setFont(font)
        self.moveButton.setStyleSheet("font: 75 12pt \"Sitka\";")
        self.moveButton.setObjectName("moveButton")
        self.verticalLayout_4.addWidget(self.moveButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.manipulatingContainer.addWidget(self.widget1)
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.load_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/img/3d-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_action.setIcon(icon3)
        self.load_action.setObjectName("load_action")
        self.save_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/img/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_action.setIcon(icon4)
        self.save_action.setObjectName("save_action")
        self.action_4 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/img/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_4.setIcon(icon5)
        self.action_4.setObjectName("action_4")
        self.rasterize_scene = QtWidgets.QAction(MainWindow)
        self.rasterize_scene.setObjectName("rasterize_scene")
        self.menu.addSeparator()
        self.menu.addAction(self.load_action)
        self.menu.addAction(self.save_action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu_2.addAction(self.rasterize_scene)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openMF"))
        self.rotateYslider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вращение вокруг оси Y</p></body></html>"))
        self.rotateXslider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вращение вокруг оси Х</p></body></html>"))
        self.rotateZslider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вращение вокруг оси Z</p></body></html>"))
        self.command_edit.setPlaceholderText(_translate("MainWindow", "Введите команду..."))
        self.addObject.setText(_translate("MainWindow", "Добавить объект"))
        self.removeObject.setText(_translate("MainWindow", "Удалить объект"))
        self.label.setText(_translate("MainWindow", "Позиция камеры"))
        self.eye_set.setText(_translate("MainWindow", "Установить"))
        self.label_2.setText(_translate("MainWindow", "Позиция цели"))
        self.center_set.setText(_translate("MainWindow", "Установить"))
        self.aroundCenter.setText(_translate("MainWindow", "Вращение камеры вокруг цели"))
        self.aroundEye.setText(_translate("MainWindow", "Вращение вокруг оси"))
        self.scaleButton.setText(_translate("MainWindow", "Масштабировать"))
        self.moveButton.setText(_translate("MainWindow", "Переместить"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "Вид"))
        self.load_action.setText(_translate("MainWindow", "Загрузить сцену"))
        self.save_action.setText(_translate("MainWindow", "Сохранить сцену"))
        self.action_4.setText(_translate("MainWindow", "Выход"))
        self.rasterize_scene.setText(_translate("MainWindow", "Растеризировать кадр"))
